### ISSUE TITLE
I'm facing the same certificate chain validation issue

### ISSUE THREAD

**Issue by metalheadcode** [teslamotors/fleet-telemetry#391]
hi guys,  I'm facing the same certificate chain validation issue. Here's my setup and what I've tried:

1. **Infrastructure Setup**:
   - Kubernetes cluster on DigitalOcean
   - Domain `fleet-telemetry.ticketskipper.com` managed by Cloudflare
   - Using cert-manager with Let's Encrypt for certificate management
   - DNS validation through Cloudflare API token

2. **Certificate Configuration**:
   - Created a ClusterIssuer for Let's Encrypt:
     ```yaml
     apiVersion: cert-manager.io/v1
     kind: ClusterIssuer
     metadata:
       name: letsencrypt-prod
     spec:
       acme:
         server: https://acme-v02.api.letsencrypt.org/directory
         email: your-email@example.com
         privateKeySecretRef:
           name: letsencrypt-prod
         solvers:
         - dns01:
             cloudflare:
               apiTokenSecretRef:
                 name: cloudflare-api-token-secret
                 key: api-token
     ```
   - Certificate is successfully issued and stored in Kubernetes secret

3. **Certificate Chain Validation**:
   - Created `validate_server.json` with:
     ```json
     {
       "hostname": "fleet-telemetry.ticketskipper.com",
       "port": 443,
       "ca": "./full-chain.pem"
     }
     ```
   - Extracted the full chain from Kubernetes secret:
     ```bash
     kubectl get secret fleet-telemetry-tls -o jsonpath='{.data.tls\.crt}' | base64 -d > full-chain.pem
     ```

4. **Validation Attempts**:
   - Running `./tools/check_server_cert.sh validate_server.json`
   - Getting error: `unable to get issuer certificate`
   - Tried using system CA bundle (`/etc/ssl/cert.pem`)
   - Tried using just the intermediate certificate
   - Tried appending ISRG Root X1 to the chain

5. **Current Status**:
   - Certificate is valid (can verify with `openssl verify`)
   - Server is accessible via HTTPS
   - Cloudflare SSL/TLS is set to "Full" mode
   - But validation script still fails with issuer certificate error

Thanks for your help!
